language: go

matrix:
  include:
  - os: linux
    dist: xenial

  - os: osx

  - os: windows
    before_install:
    - choco install make

env:
  global:
  - GO111MODULE=on
  - GOOGLE_CLOUD_PROJECT=berglas-test
  - GOOGLE_CLOUD_BUCKET=berglas-test-secrets
  - GOOGLE_CLOUD_KMS_KEY=projects/berglas-test/locations/global/keyRings/my-keyring/cryptoKeys/my-key
  - GOOGLE_CLOUD_SERVICE_ACCOUNT=berglas-test@berglas-test.iam.gserviceaccount.com
  - GOOGLE_APPLICATION_CREDENTIALS=/tmp/account.json

go:
- 1.13.x

git:
  depth: 1
  quiet: true

branches:
  only:
  - master

before_script:
- openssl aes-256-cbc -K $encrypted_c5c9a0caec9c_key -iv $encrypted_c5c9a0caec9c_iv -in ./test/account.json.enc -out /tmp/account.json -d

install: true

script: make test-acc
